assets:
  overrides:
    /: ../frontend/

server:
  rootPath: '/api/*'

database:
  driverClass: com.mysql.jdbc.Driver

  user: root

#  password:
  url: jdbc:mysql://localhost:3306/mysqldb
  properties:
    charSet: UTF-8